### ISSUE TITLE
The page you’re looking for could not be found

### ISSUE THREAD

**Issue by protonhs** [airmiha/create-shopify-app#13]
Hello
Thank you for your efforts, a friend of mine is using your code smoothly buy I don't know why it's not working for me.
after setting up everything I get an error when I try to install it , it shows : 
 " The page you’re looking for could not be found
Please make sure the web address is correct."
I checked the param values and re-checked them for 3 days now and no success.
In the console it says : 
[0] info: Checking for valid session: undefined
[0] info: Authenticating shop undefined
[0] GET /api/products 302 16.090 ms - 55

another thing is that react is listening to port 3001:
`--------------------------
[0] ===> 😊  Starting Server . . .
[0] ===>  Environment: development
[0] ===>  Listening on port: 3001
[0] --------------------------
[0] Listening on port 3001
`
So I made Ngrok pointing to 3001 too

Any help please ?
Thank you!

**Comment by airmiha** [comment]
Hey @protonhs,

How are you trying to install the app? Are you going through the Shopify App Store temp listing?

It seems that there's no shop in the request. Also, can you paste the entire log here and the exact steps you did?

**Comment by protonhs** [comment]
Thank you @airmiha 

I have followed the steps successfully till Step 4 where I had to run the project, and I saw that react is listening to 3001, so I came back and relaunched NGRok to point to 3001 and updated the adress in index.js and in the app settings.
Then I re-run the project.
Surprisingly today it's showing a bigger problem:
MACs-MacBook-Pro-2:create-shopify-app-master mac$ npm run start:dev

> create-shopify-app@0.0.1 start:dev /Users/mac/Downloads/create-shopify-app-master
> concurrently "npm run server:dev" "cd react-ui/ && npm start"

[0] 
[0] > create-shopify-app@0.0.1 server:dev /Users/mac/Downloads/create-shopify-app-master
[0] > cross-env NODE_ENV=development nodemon
[0] 
[1] 
[1] > client@0.1.0 start /Users/mac/Downloads/create-shopify-app-master/react-ui
[1] > react-scripts start
[1] 
[0] [nodemon] 1.11.0
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching: /Users/mac/Downloads/create-shopify-app-master/server/**/* webpack.config.js .env
[0] [nodemon] starting `npm run build:dev && node compiled/server.dev.js`
[0] 
[0] > create-shopify-app@0.0.1 build:dev /Users/mac/Downloads/create-shopify-app-master
[0] > cross-env NODE_ENV=development npm run webpack
[0] 
[0] 
[0] > create-shopify-app@0.0.1 webpack /Users/mac/Downloads/create-shopify-app-master
[0] > webpack --colors --display-error-details --config ./webpack.config.js
[0] 
[1] [HPM] Proxy created: function (pathname) {
[1]         return mayProxy(pathname) && pathname.match(context);
[1]       }  ->  http://localhost:3001
[1] Starting the development server...
[1] 
[0] Hash: 43e424871a67a3cc3707
[0] Version: webpack 3.11.0
[0] Time: 1545ms
[0]             Asset     Size  Chunks             Chunk Names
[0]     server.dev.js  27.4 kB       0  [emitted]  server
[0] server.dev.js.map  39.5 kB       0  [emitted]  server
[0]    [0] ./server/config/index.js 1.09 kB {0} [built]
[0]    [4] ./server/db/index.js 621 bytes {0} [built]
[0]    [5] ./server/db/models/index.js 1.13 kB {0} [built]
[0]    [6] ./server/server.js 1.69 kB {0} [built]
[0]    [8] ./server/app.js 5.01 kB {0} [built]
[0]   [19] ./server/db/connect.js 572 bytes {0} [built]
[0]   [21] ./server/db/sequelize_config.json 463 bytes {0} [built]
[0]   [22] ./server/db/models/shop.js 462 bytes {0} [built]
[0]   [23] ./server/db/session.js 835 bytes {0} [built]
[0]   [25] ./server/routes/shopify.js 10 kB {0} [built]
[0]     + 21 hidden modules
[0] Fri, 20 Apr 2018 07:27:06 GMT sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators at node_modules/sequelize/lib/sequelize.js:242:13
[0] --------------------------
[0] ===> 😊  Starting Server . . .
[0] ===>  Environment: development
[0] ===>  Listening on port: 3001
[0] --------------------------
[0] Listening on port 3001
[0] Executing (default): SELECT 1+1 AS result
[0] info: Connection has been established successfully.
[1] Compiled successfully!
[1] 
[1] You can now view client in the browser.
[1] 
[1]   Local:            http://localhost:3000/
[1]   On Your Network:  http://192.168.1.7:3000/
[1] 
[1] Note that the development build is not optimized.
[1] To create a production build, use npm run build.
[1] 
[0] info: Checking for valid session: undefined
[0] error:  TypeError: Cannot read property 'shopify' of undefined
[0]     at authMiddleware (/Users/mac/Downloads/create-shopify-app-master/compiled/webpack:/server/routes/shopify.js:226:10)
[0]     at Layer.handle [as handle_request] (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:275:10)
[0]     at Function.handle (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:174:3)
[0]     at router (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:47:12)
[0]     at Layer.handle [as handle_request] (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:275:10)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express-flash/lib/express-flash.js:31:7
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/connect-flash/lib/flash.js:21:5
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express-flash/lib/express-flash.js:22:5
[0]     at Layer.handle [as handle_request] (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:275:10)
[0]     at session (/Users/mac/Downloads/create-shopify-app-master/node_modules/express-session/index.js:189:7)
[0] GET /api/products 500 14.113 ms - 2919
[0] Error: req.flash() requires sessions
[0]     at Error (native)
[0]     at IncomingMessage._flash [as flash] (/Users/mac/Downloads/create-shopify-app-master/node_modules/connect-flash/lib/flash.js:60:41)
[0]     at ServerResponse.res.render (/Users/mac/Downloads/create-shopify-app-master/node_modules/express-flash/lib/express-flash.js:28:35)
[0]     at /Users/mac/Downloads/create-shopify-app-master/compiled/webpack:/server/app.js:129:7
[0]     at Layer.handle_error (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:71:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:315:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:275:10)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:635:15
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:260:14)
[0]     at Layer.handle [as handle_request] (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:97:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)
[0]     at next (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:275:10)
[0]     at Function.handle (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:174:3)
[0]     at router (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:47:12)
[0]     at Layer.handle [as handle_request] (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/layer.js:95:5)
[0]     at trim_prefix (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:317:13)
[0]     at /Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:284:7
[0]     at Function.process_params (/Users/mac/Downloads/create-shopify-app-master/node_modules/express/lib/router/index.js:335:12)

**Comment by airmiha** [comment]
Before we go any further, can you make sure you have a Redis server running in the background?

Try `redis-server`

**Comment by protonhs** [comment]
Thank you @airmiha for replying! It's nice of you!
redis-server did solve this morning's problem, but unfortunately, I  still find myself in front of : The page you’re looking for could not be found
I uninstalled the app and reinstalled it following the instructions, it gets installed successfully, but then the error comes.
Here are the logs of the installation : 
Ngrok  - 
HTTP Requests                                                                         
-------------                                                                         
                                                                                      
GET /activate_charge           302 Found                                              
GET /auth/callback             200 OK                                                 
GET /home                      200 OK       

Npm : 
[0] Executing (66f4d94c-c696-442b-ab83-9a25e88896b4): SELECT "id", "domain", "chargeId", "createdAt", "updatedAt" FROM "Shops" AS "Shop" WHERE "Shop"."domain" = 'apptestingstor.myshopify.com';
(long message here)
[0] Executing (66f4d94c-c696-442b-ab83-9a25e88896b4): COMMIT;
[0] GET /auth/callback?code=b1f87c382f2527051f4e936f3dc436cc&hmac=965d409e2ec37232ef98a0d59ee670bf0523d04604dc1e2b3a5fd0d559c8485d&shop=apptestingstor.myshopify.com&state=72596842cd6fb8844d451375f86d97eb&timestamp=1524232861 200 2958.643 ms - 930
[0] info: Checking for valid session: undefined
[0] GET /activate_charge?charge_id=1195081791 302 2120.009 ms - 152

Any chance I can make it work ?
Thank you!

**Comment by protonhs** [comment]
I tried accessing http://8f8fbcb5.ngrok.io/?shop=apptestingstor.myshopify.com but it gave error : Error: ENOENT: no such file or directory, open 'react-ui/build/index.html'

**Comment by airmiha** [comment]
We'll make it work :).

1. How are you trying to install the app? Are you going through the Shopify App Store temp listing?
2. Check out the first 6 comments in this thread:

https://github.com/airmiha/create-shopify-app/issues/6

Can you confirm that you have all of those things that we mentioned properly set up?

**Comment by protonhs** [comment]
Thank you! it's working now!
